# Generated by Django 5.0.2 on 2024-03-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
